name: rad12-rollback

on:
  workflow_dispatch:
    inputs:
      build_tag:
        description: 'Build tag to rollback to'
        required: true

env:
  RAD12REGISTRY: "clnx-bruh-8qr9pha7.rad12.io:40176"

jobs:
  rad12-rollback:
    runs-on: ubuntu-22.04

    steps:
      - name: Retrieve Rad12 kubeconfig from secrets
        run: mkdir /opt/rad12 && echo "${RAD12_KUBECONFIG}" > /opt/rad12/kubeconfig
        env:
          RAD12_KUBECONFIG: ${{ secrets.RAD12_KUBECONFIG }}

      - name: Generate K8s Deployment descriptor
        run: if [[ ! -d desc ]]; then mkdir desc; fi && echo -e "---\n""apiVersion"':'" apps/v1\n""kind"':'" Deployment\n""metadata"':\n'"  name"':'" app\n""  labels"':\n'"    app"':'" app\n""spec"':\n'"  replicas"':'" 1\n""  selector"':\n'"    matchLabels"':\n'"      app"':'" app\n""  template"':\n'"    metadata"':\n'"      labels"':\n'"        app"':'" app\n""    spec"':\n'"      imagePullSecrets"':\n'"        - name"':'" rad12registry\n""      containers"':\n'"        - name"':'" app\n""          image"':'" ${RAD12REGISTRY}/app:${{ github.event.inputs.build_tag }}\n""          imagePullPolicy"':'" Always\n""          envFrom"':\n'"            - secretRef"':\n'"                name"':'" app-secrets\n" > desc/Deployment.yml

      - name: Apply Deploy manifest
        run: kubectl --insecure-skip-tls-verify --kubeconfig=/opt/rad12/kubeconfig apply -f desc/Deployment.yml

      - name: Perform service rolling update
        run: kubectl --insecure-skip-tls-verify --kubeconfig=/opt/rad12/kubeconfig rollout restart deploy app
